on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy dev.ladellerby.com
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ~/me/ 
            git checkout .
            git pull 
            npm install
            export NODE_OPTIONS="--max-old-space-size=8096"
            npm run build
            pm2 restart dev-me
      - name: Deploy ladellerby.com
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ~/prod/me
            git checkout .
            git pull 
            npm install
            export NODE_OPTIONS="--max-old-space-size=8096"
            npm run build
            pm2 restart prod-me
